version: '3'

services:
  giftandgain-db:
    image: mysql:8-oracle
    environment:
      MYSQL_ROOT_PASSWORD: giftandgain123
      MYSQL_USER: giftandgain
      MYSQL_PASSWORD: giftandgain123
      MYSQL_DATABASE: giftandgain
    ports:
      - "3308:3306"
    
  inventory-management-app:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - giftandgain-db
    command: ["./wait-for-it.sh", "giftandgain-db:3306","java", "-jar", "/app/app.jar"]
