version: '3'

services:
  inventory-management-app:
    build:
      context: inventory-management
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: ["java", "-jar", "/app/app.jar"]

  frontend-giftandgain:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-giftandgain-image
    ports:
      - "9001:80"
    depends_on:
      - inventory-management-app
