version: '3'

services:

  giftandgain:
    image: mysql:8-oracle
    environment:
      MYSQL_ROOT_PASSWORD: giftandgain123
      MYSQL_USER: giftandgain
      MYSQL_PASSWORD: giftandgain123
      MYSQL_DATABASE: giftandgain
    ports:
      - "3308:3306"

  inventory-management-app:
    build:
      context: inventory-management
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - giftandgain
    command: ["./wait-for-it.sh", "giftandgain:3306","java", "-jar", "/app/app.jar"]

  frontend-giftandgain:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-giftandgain-image
    ports:
      - "9001:80"
    depends_on:
      - inventory-management-app

